version: '3.8'
services:

  employee_attendance_db:
    container_name: employee_attendance_db
    image: postgres
    restart: always
    networks:
      - employee_attendance_network
    volumes:
      - employee_attendance_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employee_attendance_db
    ports:
      - "5432:5432"


  #optional
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - employee_attendance_db
    networks:
      - employee_attendance_network
    volumes:
      - pg_admin_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


volumes:
  employee_attendance_db_volume:
  pg_admin_volume:

networks:
  employee_attendance_network: